### ISSUE TITLE
Feature highlight interferes with loading Saved View

### ISSUE THREAD

**Issue by flypdx** [TheGartrellGroup/Mapbox-GL-JS-save-view#5]
In our current setup, a feature(s) highlights when clicked by the user. If a feature is highlighted when the user Saves a View, the Saved View URL produces the following error:

"Uncaught TypeError: Cannot read property 'source' of undefined"

The Highlighted feature is not recognized as a feature found in the Layer Tree causing the above error. There should be a way to ignore highlighted features when a View is Saved. 

The gist below shows the code we use to highlight a feature on click. Please note that this code does not interact with the Layer Tree (or is ignored by the Layer Tree). 

https://gist.github.com/flypdx/d1b2e32b4f38c98bf5b516b2a2ab8234

**Comment by dnseminara** [comment]
resolved here ad32c45
